### ISSUE TITLE
关于登录的问题

### ISSUE THREAD

**Issue by pengpaige** [lvhuiyang/TIMS#1]
你好，我最近也在学 Django，请问你的项目里的登录模块需要数据库里导入哪些数据才能使用？
可不可以提供一些你的数据让我运行一下看看效果，我这边自己写进去了一点 admin 的数据，但是貌似在 amdin 页面登陆之后会访问出错，但是刷新之后显示登录了 admin 的帐号。因为刚开始学，不太清楚原理，不知道我的描述你是否能明白。
另外，请问你做这个项目主要参考了哪个项目或者教程，能否分享给我，或者你自己的文档或者笔记也行。
非常感谢！

**Comment by lvhuiyang** [comment]
Hello,额， 项目服务停了没注意看了一下是部署docker挂了...这是做的一个课程设计，做的比较糙。我没看懂你说的 “貌似在 amdin 页面登陆之后会访问出错”，我觉得首先看一下报错原因吧，知道原因才能正确debug吧。 登录原理的话无非就是（Django框架实现的）对于session的处理， 简单说下（Django处理方法）就是登录成功后端数据库存一个 记录[session_id(哈希处理应该包含user信息，具体没仔细研究),session_key,过期时间], 并且将session_id写在本地（浏览器），下次请求头部cookie中带有session_id信息，后端就能判断到具体的user了。

View层的代码在这， 其实主要是 `user = authenticate(username=..., password=...`这句

```python
class Login(View):
    def get(self, request, *args, **kwargs):
        return render(request=request, template_name="login.html", context={"messages": get_messages(request)})

    def post(self, request, *args, **kwargs):
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user:
            login(request, user)
            request.session['role'] = request.POST['role']
            return redirect(to=reverse("index"))
        else:
            messages.add_message(request, messages.INFO, '登录失败, 请检查用户名密码')
            return redirect(to=reverse("login"))
```

现在你可以登录 http://tims.lvhuiyang.cn/ 看一下效果了刚恢复了， user:lvhuiyang ,password:hello1234, 删除存在关联删除没处理，所以不要点击删除。 可以去admin看下，对比项目源码的表结构。【总的来说看这个项目的逻辑和实现可以，其他的写的太烂就不要学了】

最后教程或者学习笔记的话 Django 应该还不少吧， 我实习之后才写Django 的没怎么读过Django的书，之前都是写 Flask....  django 官方文档就挺好的（我英文不好一般看翻译版 目前v1.8）,还有就是遇到问题google查一下，《Python Web开发：测试驱动方法》看过一点有点太基础有点啰嗦...

最后的最后有问题可以多交流。

**Comment by lvhuiyang** [comment]
忘了说了web项目对外只写了 查询和修改（删除没写好），  要增加数据的话去
 admin看一下吧 http://tims.lvhuiyang.cn/admin/
